### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by IsaacWoods** [rust-osdev/acpi#1]
This is a tracking issue for getting `acpi` into a "vaguely useful" state. We should be able to parse most common ACPI tables and standard-conforming AML. I'd also like to get some testing infrastructure up and running pretty soon.

## General
- [x] ~~Land changes in `multiboot2-elf64` to support RSDP/XSDT tags ([`multiboot2-elf64/#43`](https://github.com/rust-osdev/multiboot2-elf64/pull/43))~~
- [x] ~~Construct a RSDP given a physical address~~
- [x] ~~Manually scan for the RSDP~~
- [x] ~~Parse RSDT directly, given the address, for use with `multiboot2` crate etc.~~
- [x] ~~Infrastructure for asking the kernel to map physical memory etc.~~
- [x] Flesh out 'Using' section in Readme on how to actually use the library
- [x] ~~Add support for logging with `log`~~

## Tables we should be able to parse
- [x] ~~RSDT~~
- [x] ~~XSDT~~
- [x] ~~FADT~~
- [x] ~~MADT (#20)~~ (full support for i8259 and APIC models, SAPIC, X2APIC and GIC not yet supported)
- [x] DSDT and SSDTs (#9, ...)
- [x] ~~HPET (#16)~~

## Parsing AML
- [x] ~~Basic parsing stuff (#9)~~
- [x] ~~Reliable error handling in case of invalid AML or unimplemented parsing routines (#9)~~
- [x] Be able to parse SeaBios' tables

## Testing infrastructure
- [ ] Simple OS running on headless QEMU to test SeaBios. Run on Travis.
- [ ] Script to dump users' ACPI info ([useful stuff](https://blog.fpmurphy.com/2014/12/decompiling-acpi-tables.html)) + `/proc/cpuinfo`?
- [ ] The Great Acpi Dump
- [ ] Set up test suite for running `acpi` against dumped tables
- [ ] Add SeaBios dump to dump for QEMU and Bochs support
- [ ] Test RSDP validation with individually valid/invalid RSDPs

**Comment by robert-w-gries** [comment]
Cant' wait to see how the library turns out!  Regarding this goal:

> Getting an RSDP address from the `multiboot2` crate

Is it possible to avoid dependencies on the `multiboot2` crate in this project?  If we pass the raw `RSDP` address from the kernel/bootloader to this library, it'll be easier to add support for the Rust bootloader later.

**Comment by IsaacWoods** [comment]
@robert-w-gries Thanks! I'm not sure how it'll turn out, but hopefully we'll get at least basic support going and more people can hack on it when they need something ;)

> Is it possible to avoid dependencies on the multiboot2 crate in this project?

My plan was to feature-gate the function to create it from the multiboot2 tag, but we could also just have an unsafe function where you pass the address?

I don't have a nice implementation for the manual scan anyways, but that might never be necessary if we add it to the Rust bootloader (it's nicer to do before turning paging on). Thanks, that sounds like a better solution :)

**Comment by Restioson** [comment]
@phil-opp made me aware of this project in a comment [here](https://github.com/Restioson/flower/issues/61#issuecomment-390646696). On that note, I've started a bit of AML parsing in my local branch, so maybe I could help with that? Also, @gegy1000 implemented the HPET table, so maybe he could adapt it for this as well. I mention this because the HPET is very useful as a timer for doing scheduling in OSes, and it would be useful if this library supported it.

**Comment by IsaacWoods** [comment]
Hi @Restioson - it would be great to get support for the HPET into the library; then the first useful bit of the library will actually work! Feel free to open a PR, if you're happy to.

On AML, I'm currently working on getting some basic parsing infrastructure down, which I'll push to #9  when I'm happier with it - it seems a little over-complicated atm. If I get the basics merged, more people can chip in, as the actual spec is huge. How's that sound? Of course, if you've got a better idea for the parser once it's pushed, I'm all ears - still learning the intricacies ;)

**Comment by Restioson** [comment]
I am readying a PR to manually scan for the RSDP when the computer is using BIOS (afaik, UEFI gives you the pointer to the RSDP) based off the Flower code for it.

**Comment by IsaacWoods** [comment]
Looks like we've basically finished off this initial roadmap, so I'm closing this issue. Obviously, there's still a lot to do, but it can be tracked in more specific issues.
